#!/bin/bash

# Create the directory 
mkdir /etc/nginx/servers

# Enable HTTP server
mv /etc/nginx/disabled-server-http.conf /etc/nginx/servers/http.conf

if [ -f /config/letsencrypt.config ]; then 
    . /config/letsencrypt.config

    # Let's Encrypt works by querying the web server over HTTP in order
    # to issue the certificates, so we need to start Nginx temporarily
    # now in order for certificates to be issued or renewed.
    /usr/sbin/nginx
    while [ ! -e /run/nginx.pid ]; do
      echo "Waiting for /run/nginx.pid to appear for Let's Encrypt issuance..."
      sleep 1
    done

    # Make the webroot that we will store certificates in
    mkdir /srv/letsencrypt-webroot

    # If the Let's Encrypt folder doesn't exist, create it
    if [ ! -d /config/letsencrypt ]; then
        mkdir /config/letsencrypt
    fi
    
    # Link the Let's Encrypt folder into the configuration directory
    ln -s /config/letsencrypt /etc/letsencrypt

    # Perform the Let's Encrypt certificate issuance
    /srv/letsencrypt/letsencrypt-auto certonly --keep --debug --agree-tos --webroot -w /srv/letsencrypt-webroot --email $LETS_ENCRYPT_EMAIL -d $LETS_ENCRYPT_DOMAIN

    # Add Let's Encrypt issuance to cron.monthly
    cat >/etc/cron.weekly/letsencrypt <<EOF
#!bin/bash

/srv/letsencrypt/letsencrypt-auto certonly --keep --debug --agree-tos --webroot -w /srv/letsencrypt-webroot --email $LETS_ENCRYPT_EMAIL -d $LETS_ENCRYPT_DOMAIN
EOF
    chmod a+x /etc/cron.monthly/letsencrypt

    # Enable HTTPS using the Let's Encrypt configuration
    mv /etc/nginx/disabled-server-https-letsencrypt.conf /etc/nginx/servers/https-letsencrypt.conf

    # Link /config/letsencrypt/installed to /config/letsencrypt/live/*
    rm /config/letsencrypt/installed
    ln -s $(ls -d /config/letsencrypt/live/*) /config/letsencrypt/installed

    # Kill Nginx and remove the PID file, we'll start Nginx back up
    # again with HTTPS support later
    kill -KILL $(pidof nginx)
    rm /run/nginx.pid
else
    if [ -e /config/cert.pem ]; then
        if [ -e /config/cert.key ]; then
            echo "Enabling SSL due to presence of certificates!"

            # Enable HTTPS using the manual configuration
            mv /etc/nginx/disabled-server-https-manual.conf /etc/nginx/servers/https-manual.conf
        fi
    fi
fi


