#!/bin/bash

# Enable HTTP server
mv /etc/nginx/disabled-server-http.conf /etc/nginx/server-http.conf

if [ "$LETS_ENCRYPT" == "true" ]; then
    # Let's Encrypt works by querying the web server over HTTP in order
    # to issue the certificates, so we need to start Nginx temporarily
    # now in order for certificates to be issued or renewed.
    /usr/sbin/nginx
    while [ ! -e /run/nginx.pid ]; do
      echo "Waiting for /run/nginx.pid to appear for Let's Encrypt issuance..."
      sleep 1
    done

    # Make the webroot that we will store certificates in
    mkdir /srv/letsencrypt-webroot

    # If the Let's Encrypt folder doesn't exist, create it
    if [ ! -d /config/letsencrypt ]; then
        mkdir /config/letsencrypt
    fi
    
    # Link the Let's Encrypt folder into the configuration directory
    ln -s /config/letsencrypt /etc/letsencrypt

    # Perform the Let's Encrypt certificate issuance
    /srv/letsencrypt/letsencrypt-auto certonly --keep --debug --staging --agree-tos --webroot -w /srv/letsencrypt-webroot -e $LETS_ENCRYPT_EMAIL -d $LETS_ENCRYPT_DOMAIN

    # Enable HTTPS using the Let's Encrypt configuration
    mv /etc/nginx/disabled-server-https-letsencrypt.conf /etc/nginx/server-https-letsencrypt.conf

    # Link /etc/letsencrypt/installed to /etc/letsencrypt/live/*
    ln -s /etc/letsencrypt/live/* /etc/letsencrypt/installed

    # Kill Nginx and remove the PID file, we'll start Nginx back up
    # again with HTTPS support later
    kill -KILL $(</run/nginx.pid)
    rm /run/nginx.pid
else
    if [ -e /config/cert.pem ]; then
        if [ -e /config/cert.key ]; then
            echo "Enabling SSL due to presence of certificates!"

            # Enable HTTPS using the manual configuration
            mv /etc/nginx/disabled-server-https-manual.conf /etc/nginx/server-https-manual.conf
        fi
    fi
fi


