#!/bin/bash

# Touch log file and PID file to make sure they're writable
touch /var/log/aphlict.log
chown git:wwwgrp-phabricator /var/log/aphlict.log

# Copy ws module from global install
cp -Rv /usr/lib/node_modules /srv/phabricator/phabricator/support/aphlict/server/
chown -Rv git:wwwgrp-phabricator /srv/phabricator/phabricator/support/aphlict/server/node_modules

# Start the Phabricator notification server
pushd /srv/phabricator/phabricator
sudo -u git bin/aphlict start
popd
