#!/bin/bash

if [ ! -f /is-baking ]; then
  # Run SSHD
  /usr/sbin/sshd -f /etc/phabricator-ssh/sshd_config.phabricator

  # Wait for /run/sshd-phabricator.pid to appear and copy it.
  while [ ! -e /run/sshd-phabricator.pid ]; do
    echo "Waiting for /run/sshd-phabricator.pid to appear..."
    sleep 1
  done
  cp /run/sshd-phabricator.pid /run/watch/sshd-phabricator
fi

